  INFO root [2018-05-20 11:21:04,805] - 
  INFO root [2018-05-20 11:21:04,826] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-20 11:21:05,637] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-20 11:21:05,639] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-20 11:21:05,639] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-20 11:21:06,241] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-20 11:21:06,269] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-20 11:21:06,274] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:49756 )
  INFO root [2018-05-20 11:21:06,274] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:49756, SOMAXCONN=128.
  INFO root [2018-05-20 11:21:06,275] - server-configs:
  INFO root [2018-05-20 11:21:06,275] - 	internalAddr : 192.168.0.104:49756
  INFO root [2018-05-20 11:21:06,276] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-20 11:21:06,276] - 	componentID : 9000
  INFO root [2018-05-20 11:21:06,990] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 27066. PID: 5832 ----
  INFO root [2018-05-20 11:21:06,991] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-20 11:21:06,992] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-20 11:21:07,061] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-20 11:21:13,110] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-20 11:21:13,232] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-20 11:21:13,352] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-20 11:21:15,352] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-20 11:21:15,512] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-20 11:21:15,566] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-20 11:21:15,600] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-20 11:21:16,232] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-20 11:21:17,944] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-20 11:21:17,946] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-20 11:21:18,167] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-20 11:21:18,168] - TelnetServer server is running on port 31000
  INFO root [2018-05-20 11:21:18,941] - ---- loginapp is running ----
 DEBUG root [2018-05-20 11:21:18,986] - Components::process(): Request for the process of identity...
  INFO root [2018-05-20 11:21:26,394] - Components::findComponents: find logger(1)...
  INFO root [2018-05-20 11:21:26,473] - Components::findComponents: found logger, addr:192.168.0.104:49749
  INFO root [2018-05-20 11:21:26,474] - Components::addComponent: reset orderLog, uid=27066!
  INFO root [2018-05-20 11:21:26,475] - Components::addComponent[logger], uid=27066, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-20 11:21:26,498] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-05-20 11:21:27,579] - Forwarding logs to logger[192.168.0.104:49749/0/0/0]...
  INFO root [2018-05-20 11:21:30,024] - 
  INFO root [2018-05-20 11:21:30,024] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-20 11:21:30,025] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-20 11:21:30,025] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-20 11:21:30,025] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-20 11:21:30,027] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-20 11:21:30,027] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-20 11:21:30,028] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:49776 )
  INFO root [2018-05-20 11:21:30,028] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:49776, SOMAXCONN=128.
  INFO root [2018-05-20 11:21:30,028] - server-configs:
  INFO root [2018-05-20 11:21:30,029] - 	internalAddr : 192.168.0.104:49776
  INFO root [2018-05-20 11:21:30,029] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-20 11:21:30,029] - 	componentID : 9000
  INFO root [2018-05-20 11:21:31,703] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 27232. PID: 5844 ----
  INFO root [2018-05-20 11:21:31,703] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-20 11:21:31,704] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-20 11:21:31,704] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-20 11:21:31,825] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-20 11:21:31,826] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-20 11:21:31,826] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-20 11:21:31,829] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-20 11:21:31,829] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-20 11:21:31,829] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-20 11:21:31,830] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-20 11:21:31,857] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-20 11:21:31,894] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-20 11:21:31,894] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-20 11:21:31,897] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-20 11:21:31,897] - TelnetServer server is running on port 31000
  INFO root [2018-05-20 11:21:32,176] - ---- loginapp is running ----
 DEBUG root [2018-05-20 11:21:32,177] - Components::process(): Request for the process of identity...
  INFO root [2018-05-20 11:21:39,277] - Components::findComponents: find logger(1)...
  INFO root [2018-05-20 11:21:39,303] - Components::findComponents: found logger, addr:192.168.0.104:49770
  INFO root [2018-05-20 11:21:39,304] - Components::addComponent: reset orderLog, uid=27232!
  INFO root [2018-05-20 11:21:39,304] - Components::addComponent[logger], uid=27232, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-20 11:21:39,306] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-05-20 11:21:40,409] - Forwarding logs to logger[192.168.0.104:49770/0/0/0]...
 ERROR root [2018-05-20 11:22:02,626] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-20 11:22:02,627] - The following logs sent to logger failed:
  WARN root [2018-05-20 11:22:02,628] - ==> [2018-05-20 11:22:02 626] TCPPacketReceiver::processPendingEvents(192.168.0.104:49770): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-20 11:22:02,628] - ==> [2018-05-20 11:22:02 627] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-20 11:22:03,563] - 
  INFO root [2018-05-20 11:22:03,563] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-20 11:22:03,563] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-20 11:22:03,563] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-20 11:22:03,564] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-20 11:22:03,565] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-20 11:22:03,566] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-20 11:22:03,567] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:49801 )
  INFO root [2018-05-20 11:22:03,567] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:49801, SOMAXCONN=128.
  INFO root [2018-05-20 11:22:03,567] - server-configs:
  INFO root [2018-05-20 11:22:03,567] - 	internalAddr : 192.168.0.104:49801
  INFO root [2018-05-20 11:22:03,567] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-20 11:22:03,567] - 	componentID : 9000
  INFO root [2018-05-20 11:22:05,242] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 27343. PID: 5004 ----
  INFO root [2018-05-20 11:22:05,243] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-20 11:22:05,243] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-20 11:22:05,243] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-20 11:22:05,365] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-20 11:22:05,365] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-20 11:22:05,366] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-20 11:22:05,368] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-20 11:22:05,369] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-20 11:22:05,369] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-20 11:22:05,369] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-20 11:22:05,402] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-20 11:22:05,431] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-20 11:22:05,432] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-20 11:22:05,434] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-20 11:22:05,434] - TelnetServer server is running on port 31000
  INFO root [2018-05-20 11:22:05,724] - ---- loginapp is running ----
 DEBUG root [2018-05-20 11:22:05,725] - Components::process(): Request for the process of identity...
  INFO root [2018-05-20 11:22:12,814] - Components::findComponents: find logger(1)...
  INFO root [2018-05-20 11:22:12,891] - Components::findComponents: found logger, addr:192.168.0.104:49799
  INFO root [2018-05-20 11:22:12,892] - Components::addComponent: reset orderLog, uid=27343!
  INFO root [2018-05-20 11:22:12,892] - Components::addComponent[logger], uid=27343, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-20 11:22:12,893] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-05-20 11:22:13,995] - Forwarding logs to logger[192.168.0.104:49799/0/0/0]...
 ERROR root [2018-05-20 11:22:20,355] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-20 11:22:20,356] - The following logs sent to logger failed:
  WARN root [2018-05-20 11:22:20,357] - ==> [2018-05-20 11:22:20 355] TCPPacketReceiver::processPendingEvents(192.168.0.104:49799): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-20 11:22:20,357] - ==> [2018-05-20 11:22:20 356] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-20 11:23:32,158] - 
  INFO root [2018-05-20 11:23:32,159] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-20 11:23:32,159] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-20 11:23:32,159] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-20 11:23:32,159] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-20 11:23:32,161] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-20 11:23:32,161] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-20 11:23:32,163] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:49859 )
  INFO root [2018-05-20 11:23:32,163] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:49859, SOMAXCONN=128.
  INFO root [2018-05-20 11:23:32,163] - server-configs:
  INFO root [2018-05-20 11:23:32,163] - 	internalAddr : 192.168.0.104:49859
  INFO root [2018-05-20 11:23:32,163] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-20 11:23:32,163] - 	componentID : 9000
  INFO root [2018-05-20 11:23:33,843] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 27634. PID: 3032 ----
  INFO root [2018-05-20 11:23:33,844] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-20 11:23:33,844] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-20 11:23:33,844] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-20 11:23:33,968] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-20 11:23:33,968] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-20 11:23:33,968] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-20 11:23:33,971] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-20 11:23:33,972] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-20 11:23:33,972] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-20 11:23:33,972] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-20 11:23:34,008] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-20 11:23:34,042] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-20 11:23:34,043] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-20 11:23:34,045] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-20 11:23:34,045] - TelnetServer server is running on port 31000
  INFO root [2018-05-20 11:23:34,369] - ---- loginapp is running ----
 DEBUG root [2018-05-20 11:23:34,369] - Components::process(): Request for the process of identity...
  WARN root [2018-05-20 11:23:34,699] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20178, errorno=10048
  INFO root [2018-05-20 11:23:41,825] - Components::findComponents: find logger(1)...
  INFO root [2018-05-20 11:23:41,842] - Components::findComponents: found logger, addr:192.168.0.104:49855
  INFO root [2018-05-20 11:23:41,842] - Components::addComponent: reset orderLog, uid=27634!
  INFO root [2018-05-20 11:23:41,843] - Components::addComponent[logger], uid=27634, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-20 11:23:41,845] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-05-20 11:23:42,946] - Forwarding logs to logger[192.168.0.104:49855/0/0/0]...
  INFO root [2018-05-20 11:24:43,984] - 
  INFO root [2018-05-20 11:24:43,985] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-20 11:24:43,985] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-20 11:24:43,985] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-20 11:24:43,985] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-20 11:24:43,987] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-20 11:24:43,987] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-20 11:24:43,988] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:49896 )
  INFO root [2018-05-20 11:24:43,988] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:49896, SOMAXCONN=128.
  INFO root [2018-05-20 11:24:43,988] - server-configs:
  INFO root [2018-05-20 11:24:43,989] - 	internalAddr : 192.168.0.104:49896
  INFO root [2018-05-20 11:24:43,989] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-20 11:24:43,989] - 	componentID : 9000
  INFO root [2018-05-20 11:24:45,646] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 27866. PID: 3892 ----
  INFO root [2018-05-20 11:24:45,647] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-20 11:24:45,647] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-20 11:24:45,647] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-20 11:24:45,769] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-20 11:24:45,770] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-20 11:24:45,770] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-20 11:24:45,773] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-20 11:24:45,773] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-20 11:24:45,773] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-20 11:24:45,774] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-20 11:24:45,800] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-20 11:24:45,828] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-20 11:24:45,828] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-20 11:24:45,830] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-20 11:24:45,830] - TelnetServer server is running on port 31000
  INFO root [2018-05-20 11:24:46,114] - ---- loginapp is running ----
 DEBUG root [2018-05-20 11:24:46,114] - Components::process(): Request for the process of identity...
  INFO root [2018-05-20 11:24:53,230] - Components::findComponents: find logger(1)...
  INFO root [2018-05-20 11:24:53,316] - Components::findComponents: found logger, addr:192.168.0.104:49891
  INFO root [2018-05-20 11:24:53,316] - Components::addComponent: reset orderLog, uid=27866!
  INFO root [2018-05-20 11:24:53,317] - Components::addComponent[logger], uid=27866, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-20 11:24:53,320] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-05-20 11:24:54,423] - Forwarding logs to logger[192.168.0.104:49891/0/0/0]...
 ERROR root [2018-05-20 11:24:54,983] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-20 11:24:54,986] - The following logs sent to logger failed:
  WARN root [2018-05-20 11:24:54,987] - ==> [2018-05-20 11:24:54 981] TCPPacketReceiver::processPendingEvents(192.168.0.104:49891): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-20 11:24:54,987] - ==> [2018-05-20 11:24:54 983] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-20 11:25:40,331] - 
  INFO root [2018-05-20 11:25:40,331] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-20 11:25:40,331] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-20 11:25:40,332] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-20 11:25:40,332] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-20 11:25:40,334] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-20 11:25:40,334] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-20 11:25:40,335] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:49931 )
  INFO root [2018-05-20 11:25:40,335] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:49931, SOMAXCONN=128.
  INFO root [2018-05-20 11:25:40,335] - server-configs:
  INFO root [2018-05-20 11:25:40,335] - 	internalAddr : 192.168.0.104:49931
  INFO root [2018-05-20 11:25:40,335] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-20 11:25:40,335] - 	componentID : 9000
  INFO root [2018-05-20 11:25:42,000] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 28052. PID: 5368 ----
  INFO root [2018-05-20 11:25:42,000] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-20 11:25:42,001] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-20 11:25:42,001] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-20 11:25:42,123] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-20 11:25:42,123] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-20 11:25:42,124] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-20 11:25:42,126] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-20 11:25:42,127] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-20 11:25:42,127] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-20 11:25:42,127] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-20 11:25:42,154] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-20 11:25:42,181] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-20 11:25:42,181] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-20 11:25:42,183] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-20 11:25:42,183] - TelnetServer server is running on port 31000
  INFO root [2018-05-20 11:25:42,482] - ---- loginapp is running ----
 DEBUG root [2018-05-20 11:25:42,482] - Components::process(): Request for the process of identity...
  INFO root [2018-05-20 11:25:49,543] - Components::findComponents: find logger(1)...
  INFO root [2018-05-20 11:25:49,587] - Components::findComponents: found logger, addr:192.168.0.104:49928
  INFO root [2018-05-20 11:25:49,588] - Components::addComponent: reset orderLog, uid=28052!
  INFO root [2018-05-20 11:25:49,589] - Components::addComponent[logger], uid=28052, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-20 11:25:49,590] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-05-20 11:25:49,693] - Components::findComponents: found dbmgr, addr:192.168.0.104:49930
  INFO root [2018-05-20 11:25:49,694] - Components::addComponent: reset orderLog, uid=28052!
  INFO root [2018-05-20 11:25:49,694] - Components::addComponent[dbmgr], uid=28052, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-20 11:25:49,695] - Components::findComponents: found dbmgr, addr:192.168.0.104:49930
  WARN root [2018-05-20 11:25:50,695] - Forwarding logs to logger[192.168.0.104:49928/0/0/0]...
 ERROR root [2018-05-20 11:26:07,784] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-20 11:26:07,785] - The following logs sent to logger failed:
  WARN root [2018-05-20 11:26:07,785] - ==> [2018-05-20 11:26:07 783] TCPPacketReceiver::processPendingEvents(192.168.0.104:49928): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-20 11:26:07,786] - ==> [2018-05-20 11:26:07 785] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-20 11:26:07,824] - TCPPacketReceiver::processPendingEvents(192.168.0.104:49930): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-20 11:26:07,825] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-20 11:26:07,828] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-20 11:26:07,830] - onLoginAppShutDown()
  INFO root [2018-05-20 11:26:07,830] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-20 11:26:07,831] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-20 11:26:07,831] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-20 11:26:07,831] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-20 11:26:07,831] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-20 11:26:07,831] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-20 11:26:07,831] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-20 11:26:07,831] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-20 11:26:07,832] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-20 11:26:07,832] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-20 11:26:07,866] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-20 11:26:07,866] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-05-20 11:26:08,881] - 
  INFO root [2018-05-20 11:26:08,881] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-20 11:26:08,882] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-20 11:26:08,882] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-20 11:26:08,882] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-20 11:26:08,884] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20013 )
  INFO root [2018-05-20 11:26:08,884] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20013, SOMAXCONN=128.
  INFO root [2018-05-20 11:26:08,885] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:49973 )
  INFO root [2018-05-20 11:26:08,885] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:49973, SOMAXCONN=128.
  INFO root [2018-05-20 11:26:08,885] - server-configs:
  INFO root [2018-05-20 11:26:08,885] - 	internalAddr : 192.168.0.104:49973
  INFO root [2018-05-20 11:26:08,885] - 	externalAddr : 192.168.0.104:20013
  INFO root [2018-05-20 11:26:08,885] - 	componentID : 9000
  INFO root [2018-05-20 11:26:10,568] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 28143. PID: 3260 ----
  INFO root [2018-05-20 11:26:10,568] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-20 11:26:10,569] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-20 11:26:10,569] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-20 11:26:10,697] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-20 11:26:10,698] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-20 11:26:10,698] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-20 11:26:10,702] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-20 11:26:10,703] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-20 11:26:10,703] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-20 11:26:10,704] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-20 11:26:10,742] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-20 11:26:10,777] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-20 11:26:10,777] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-20 11:26:10,779] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-20 11:26:10,779] - TelnetServer server is running on port 31000
  INFO root [2018-05-20 11:26:11,074] - ---- loginapp is running ----
 DEBUG root [2018-05-20 11:26:11,074] - Components::process(): Request for the process of identity...
