  INFO root [2018-04-29 15:56:12,101] - 
  INFO root [2018-04-29 15:56:12,269] - -----------------------------------------------------------------------------------------


  INFO root [2018-04-29 15:56:12,294] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-04-29 15:56:12,294] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-04-29 15:56:12,295] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-04-29 15:56:12,303] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-04-29 15:56:12,303] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-04-29 15:56:12,306] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:51798 )
  INFO root [2018-04-29 15:56:12,306] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:51798, SOMAXCONN=128.
  INFO root [2018-04-29 15:56:12,306] - server-configs:
  INFO root [2018-04-29 15:56:12,306] - 	internalAddr : 192.168.0.106:51798
  INFO root [2018-04-29 15:56:12,306] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-04-29 15:56:12,307] - 	componentID : 9000
  INFO root [2018-04-29 15:56:14,105] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 21461. PID: 19544 ----
  INFO root [2018-04-29 15:56:14,105] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-04-29 15:56:14,106] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-04-29 15:56:14,106] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-04-29 15:56:14,273] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-04-29 15:56:14,273] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-04-29 15:56:14,274] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-04-29 15:56:14,277] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-04-29 15:56:14,277] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-04-29 15:56:14,277] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-04-29 15:56:14,278] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-04-29 15:56:14,303] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-04-29 15:56:14,329] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-04-29 15:56:14,329] - Script::install(): KBExtra is successfully!
S_INFO root [2018-04-29 15:56:14,368] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-04-29 15:56:14,368] - TelnetServer server is running on port 31000
  INFO root [2018-04-29 15:56:14,645] - ---- loginapp is running ----
 DEBUG root [2018-04-29 15:56:14,645] - Components::process(): Request for the process of identity...
  INFO root [2018-04-29 15:56:21,709] - Components::findComponents: find logger(1)...
  INFO root [2018-04-29 15:56:21,796] - Components::findComponents: found logger, addr:192.168.0.106:51799
  INFO root [2018-04-29 15:56:21,797] - Components::addComponent: reset orderLog, uid=21461!
  INFO root [2018-04-29 15:56:21,797] - Components::addComponent[logger], uid=21461, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-04-29 15:56:21,800] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-04-29 15:56:21,902] - Components::findComponents: found dbmgr, addr:192.168.0.106:51795
  INFO root [2018-04-29 15:56:21,903] - Components::addComponent: reset orderLog, uid=21461!
  INFO root [2018-04-29 15:56:21,904] - Components::addComponent[dbmgr], uid=21461, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-04-29 15:56:21,906] - Components::findComponents: found dbmgr, addr:192.168.0.106:51795
  WARN root [2018-04-29 15:56:22,907] - Forwarding logs to logger[192.168.0.106:51799/0/0/0]...
 ERROR root [2018-04-29 15:56:34,323] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-04-29 15:56:34,345] - The following logs sent to logger failed:
  WARN root [2018-04-29 15:56:34,345] - ==> [2018-04-29 15:56:34 319] TCPPacketReceiver::processPendingEvents(192.168.0.106:51799): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-04-29 15:56:34,345] - ==> [2018-04-29 15:56:34 324] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-04-29 15:56:34,400] - TCPPacketReceiver::processPendingEvents(192.168.0.106:51795): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-04-29 15:56:34,405] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-04-29 15:56:34,427] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-04-29 15:56:34,429] - onLoginAppShutDown()
  INFO root [2018-04-29 15:56:34,429] - Shutdowner::onShutdown: shutting down
  INFO root [2018-04-29 15:56:34,429] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-04-29 15:56:34,429] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-04-29 15:56:34,429] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-04-29 15:56:34,429] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-04-29 15:56:34,430] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-04-29 15:56:34,430] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-04-29 15:56:34,430] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-04-29 15:56:34,430] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-04-29 15:56:34,430] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-04-29 15:56:34,439] - Script::uninstall(): is successfully!
 DEBUG root [2018-04-29 15:56:34,439] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-04-29 15:56:34,739] - ThreadPool::destroy(): waiting for thread(2)[0x68c950,0x68c8e8,], try=1
